*  /SCRIPT/   31 JULY 1968  1008:27

(RPLQQ FRANCAIS
PRIORITY
   0
RULES
   (DEUTSCH))

(RPLQQ SVENSKA
PRIORITY
   0
RULES
   (DEUTSCH))

(RPLQQ ITALIANO
PRIORITY
   0
RULES
   (DEUTSCH))

(RPLQQ ESPANOL
PRIORITY
   0
RULES
   (DEUTSCH))

(RPLQQ HELLO
PRIORITY
   0
RULES
   (((0)
         (NIL)
         (HOW DO YOU DO ","))))

(RPLQQ COMPUTER
PRIORITY
   0
RULES
   (((0)
         (NIL)
         (DO COMPUTERS WORRY YOU)
         (WHY DO YOU MENTION COMPUTERS)
         (WHAT DO YOU THINK MACHINES HAVE TO DO WITH YOUR PROBLEMS)
         (DO'T YOU THINK COMPUTERS CAN HELP PEOPLE))))
