;  <SOURCES>SCRIPT.;1   MON 24-APRI-72 10:01AM

  (PROGN (LISPXPRIN1 (QUOTE "FILE CREATED ")
                     T)
         (LISPXPRIN1 (QUOTE "22-APR-72 23:26:05")
                     T)
         (LISPXPRIN1 T))
  (SETQQ WDLIST
         (SORRY DONT CANT WONT REMEMBER IF DREAMT DREAMED DREAM DREAMS
                HOW WHEN ALIKE SAME CERTAINLY FEEL THINK BELIEVE WISH
                MY NONE PERHAPS MAYBE NAME DEUTSCH FRANCAIS SVENSKA
                ITALIANO ESPANOL HELLO COMPUTER MACHINE MACHINES
                COMPUTERS AM ARE YOUR WAS WERE ME YOUR'R I'M MYSELF
                YOURSELF MOTHER MOM DAD FATHER SISTER BROTHER WIFE
                CHILDREN I YOU XXYYZZ YES NO CAN IS WHERE WHAT XXWHAT
                BECAUSE WHY EVERYONE EVERYBODY NOBODY NOONE ALWAYS LIKE
                DIT OH EVERY DO GIRLS WOMEN BOY GIRL MAN WOMEN SEXY
                SEXUAL SEX FRIENDLY FRIEND CRY LAUGH LOVE HATE DISLKIE))
  [RPLQQ SORRY PRIORITY 2 RULES
         (((0)
           (NIL)
           (APOLOGIES AE NOT NECESSARY %,)
           (WHAT FEELINGS DO YOU HAVE WHEN YOU APOLOGIZE]
  (RPLQQ DONT TRANSLATEION DON'T)
  (RPLQQ CANT TRANSLATEION CAN'T)
  (RPLQQ WONT TRANSLATEION WON'T)
  [RPLQQ REMEMBER PRIORITY 5 RULES
         (((REMEMBER 0)
           (NIL)
           (PRE (DO I REMEMBER 2)
                REMEMBER))
          ((YOU REMEMBER 0)
           (NIL)
           (DO YOU OFTEN THINK OF 3)
           (WHAT ELSE DOES THINKING OF 3 BRING TO MIND)
           (WHAT ELSE DO YOU REMEMBER)
           (WHAY DO YOU REMEMBER 3 JUST NOW)
           (WHAT IS THE PRESENT SITUATION REMINDS YOU OF 3)
           (WHAT I^@THE CONNECTION BETWEEN ME AND 3))
          ((DO I REMBMER 0)
           (NIL)
           (WHY DID YOU THINK I WOULD FORGET 4)
           (WHY DO YOU THINK I SHOULD RECALL 4 NOW)
           (WHAT ABOUT 4]
  [RPLQQ IF PRIORITY 3 RULES (((0 IF 0)
           (NIL)
           (DO YOU THINK ITS LIKELY THAT 3)
           (DO YOU WISH THAT 3)
           (WHAT DO YOU THINK ABOUT 3)
           (REALLY "," IF 3]
